(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var ORa=function(a){a=String(a);var b=a.indexOf(".");-1===b&&(b=a.length);var c="-"===a[0]?"-":"";c&&(a=a.substring(1));return c+(0,g.eNa)("0",Math.max(0,2-b))+a},PRa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},QRa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},c6=function(a){"number"===typeof a?(this.date=RRa(a,0,1),b6(this,1)):g.Ma(a)?(this.date=RRa(a.getFullYear(),a.getMonth(),a.getDate()),b6(this,a.getDate())):(this.date=new Date(g.Qa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),b6(this,a))},RRa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},b6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},d6=function(a,b){g.FN.call(this,a,{G:"div",
L:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},U:[{G:"div",L:"ytp-reminder-menu-contents",U:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.i=b;this.B=[];this.menuPopupRenderer=void 0;this.items=this.Fa("ytp-reminder-menu-items");this.hide()},TRa=function(a){var b=SRa(a),c=0,d={};
for(c=0;c<b.length;d={BB:d.BB},c++){var e=a.B[c];e||(e=new g.W({G:"div",L:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},U:[{G:"div",L:"ytp-reminder-menu-item-icon",ya:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",ya:"{{text}}"}]}),d.BB=c,e.Ra("click",function(l){return function(){var m=l.BB;a.Eb();m=SRa(a)[m];a.ea("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Da(a.items),a.B[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=PRa();break;case "NOTIFICATIONS_NONE":h=QRa();break;case "NOTIFICATIONS_ACTIVE":h=g.UK()}f=f.text?g.eA(f.text):"";e.update({icon:h,text:f})}for(;c<a.B.length;)a.B.pop().dispose();0===c?a.Eb():a.wd(a.i)},SRa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},e6=function(a){g.W.call(this,{G:"div",
U:[{G:"button",Ga:["ytp-offline-slate-button","ytp-button"],U:[{G:"div",L:"ytp-offline-slate-button-icon",ya:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",ya:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.i=null;(this.D=this.Fa("ytp-offline-slate-button"))&&this.T(this.D,"click",this.I);this.hide()},URa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);f6(a)},f6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.eA(b.toggledText):"";a.update({text:c,icon:g6(b.toggledIcon)})}else c=b.defaultText?g.eA(b.defaultText):"",a.update({text:c,icon:g6(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=VRa(a))?(c=b.text?g.eA(b.text):"",a.update({text:c,icon:g6(b.icon)}),a.show()):a.hide():a.hide()},XRa=function(a,b,c){a.C||(a.C=new g.Qx(a.J.V().Ug));
var d={context:g.Cv(a.C.config_||g.Dv())};g.py()&&(d.context.clientScreenNonce=g.py());d.params=c;g.Ev(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){WRa(a)},
onTimeout:function(){WRa(a)}})},WRa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,f6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,f6(a))},g6=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return PRa();case "NOTIFICATIONS_NONE":return QRa();case "NOTIFICATIONS_ACTIVE":return g.UK();default:return null}},VRa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.r(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},h6=function(a){g.W.call(this,{G:"div",
L:"ytp-offline-slate",U:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",U:[{G:"span",L:"ytp-offline-slate-icon",U:[{G:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},U:[{G:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",U:[{G:"div",L:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},ya:"{{mainText}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",ya:"{{subtitleText}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",Ga:["ytp-offline-slate-close-button","ytp-button"],U:[g.PK()]},{G:"button",Ga:["ytp-offline-slate-open-button","ytp-button"],U:[g.OK()]},{G:"div",L:"ytp-offline-slate-trailer-chip",ya:"Trailer"}]});var b=
this;this.api=a;this.i=this.u=null;this.background=this.Fa("ytp-offline-slate-background");this.B=this.Fa("ytp-offline-slate-bar");this.D=new g.L(function(){g.M(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.L(function(){g.M(b.element,"ytp-offline-slate-collapsed")},15E3);
g.I(this,this.C);g.I(this,this.D);this.countdownTimer=new g.L(this.AO,1E3,this);this.T(a,"presentingplayerstatechange",this.DO);this.T(a,"livestatedata",this.Qa);a=this.Fa("ytp-offline-slate-close-button");this.T(a,"click",function(){g.M(b.element,"ytp-offline-slate-collapsed")});
a=this.Fa("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Uq(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Qa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Wi;var c=8===this.api.getPresentingPlayerType();g.N(this.element,"ytp-offline-slate-premiere-trailer",a);g.N(this.element,"ytp-offline-slate-hide-background",c)},i6=function(a,b,c){var d,e,f,h;
if(b){var l=null!=b.subtitleText?g.eA(b.subtitleText):"";c=c?c:null!=b.mainText?g.eA(b.mainText):"";b=null!==(h=null===(f=null===(e=null===(d=b.mainText)||void 0===d?void 0:d.accessibility)||void 0===e?void 0:e.accessibilityData)||void 0===f?void 0:f.label)&&void 0!==h?h:c;a.update({mainText:c,subtitleText:l,label:b});g.N(a.element,"ytp-offline-slate-single-text-line",!l);g.N(a.B,"ytp-offline-slate-bar-hidden",!c&&!l)}},j6=function(a,b){var c=(0,g.Q)();
this.trigger=a;this.i=b;this.B=c},l6=function(a){g.WM.call(this,a);
var b=this;this.K=!1;this.S=0;this.D=!1;this.u=new g.L(function(){var e=b.player.V(),f=b.getVideoData();if(k6(b))if(YRa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.wi(b.heartbeatParams.url,{request_id:g.lja()}),f.Pa&&(e=g.wi(e,{vvt:f.Pa}),f.mdxEnvironment&&(e=g.wi(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.wi(e,{access_token:f.oauthToken})),ZRa(b,f,e))}else $Ra(b),aSa(b,e,f)},0);
this.i=this.heartbeatParams=null;this.C=!1;this.I=new g.$d(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ma=new g.Qx(void 0);this.X=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new c6).date.getTimezoneOffset();this.B=new g.iD(this);g.I(this,this.u);g.I(this,this.B);$Ra(this);bSa(this);this.B.T(a,"heartbeatparams",this.Ew);this.B.T(a,"presentingplayerstatechange",this.pQ);this.B.T(a,"videoplayerreset",this.qQ);this.B.T(a,g.$z("heartbeat"),this.onCueRangeEnter);this.C&&this.i&&
cSa(this,this.i);var c=new g.Yz(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.Yz(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Ad([c,d]);dSa(this)},dSa=function(a){var b=a.getVideoData();
if(b.Lh){var c=b.botguardData;c&&(a=a.player.V(),b=(b=b.Ba||"")?"c1b"in g.Os(b):!1,g.Iua(c,a,b))}},$Ra=function(a){var b=a.getVideoData();
if(b.Lh&&(b=new g.Oua(b),g.oM.Zd()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Ba){var d=g.Pua(b);if(d){c={};var e={};d=d.split("&");d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=eSa[Number(e.r1c)]);c.challenge=b.videoData.Ba}}a.attestationResponse=c||void 0}},YRa=function(a){var b=a.getVideoData();
if(!g.vG(a.getVideoData())||b.nH)return!1;if(b.useInnertubeDrmService()&&b.I){a="playready"===b.I.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.I.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.eE(b.I)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},m6=function(a){if(YRa(a))return!!a.heartbeatParams;
var b=a.player.V(),c=a.getVideoData();return b.N("html5_heartbeat_wait_for_drm_killswitch")||!g.vG(a.getVideoData())||!c.useInnertubeDrmService()||c.Vg||c.aF?!!c.heartbeatToken:!1},n6=function(a,b){if(!a.u.isActive()&&a.K){var c=a.getVideoData();
if(m6(a)||c.isLivePlayback){if(void 0===b)if(a.D){var d;b=a.C?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().QO||6E4}else b=1E3;a.u.start(b)}}},ZRa=function(a,b,c){b.bj&&(c=g.wi(c,{internalipoverride:b.bj}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.xb&&(d.kpt=b.xb);c=g.wi(c,d);g.Ht(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&k6(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=fSa(e);if(f){a.player.Ma("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(gSa))?"0"===h[1]?0:1:-1;hSa(a,f,e,h)}},
onError:function(e){k6(a)&&o6(a,!0,"net-"+e.status)},
onTimeout:function(){k6(a)&&o6(a,!0,"timeout")},
withCredentials:!0})},k6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.T(a.player.zb(a.getPlayerType()),4)?!1:m6(a)||b.isLivePlayback?!0:(p6(a),!1)},aSa=function(a,b,c){var d,e,f,h={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!==(d=a.Z)&&void 0!==d?d:c.heartbeatServerData};a.X=a.attestationResponse;c.Lh&&(h.attestationResponse=a.X);var l=g.TM(c),m=null!==(e=l.client)&&void 0!==e?e:{};m.utcOffsetMinutes=a.utcOffsetMinutes;h.context=l;h.cpn=c.clientPlaybackNonce;if(l="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=l;m={heartbeatChecks:[]};if(l=c.getPlayerResponse())c.heartbeatToken&&(h.heartbeatToken=c.heartbeatToken),
(l=l.playabilityStatus)&&(l=l.liveStreamability)&&l.liveStreamabilityRenderer&&m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.lF(b)){m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var n=iSa(a);l={};null!==n&&(l.clientPlayerPositionUtcMillis=n);n=null===(f=a.player.vb())||void 0===f?void 0:g.jN(f);n=(null===n||void 0===n?void 0:n.freePreviewWatchedDuration)||0;0<n&&(l.freePreviewWatchedDuration={seconds:""+
n});m.unpluggedParams=l}h.heartbeatRequestParams=m;b.N("enable_linear_player_handling")&&c.isLivePlayback&&(b=iSa(a),null!==b&&(h.playbackState||(h.playbackState={}),h.playbackState.playbackPosition={utcTimeMillis:b}));b={timeout:3E4,onSuccess:function(p){var q;if(!a.u.isActive()&&k6(a)){var t=a.getVideoData(),u=t.Lh&&null==a.X;t.Lh=!(null===(q=p.heartbeatAttestationConfig)||void 0===q||!q.requiresAttestation)||u;q=p.playabilityStatus;t=JSON.stringify(q)||"{}";p.authenticationMismatch&&a.player.Ca("authshear",
"");u=-1;var x=p.playabilityStatus;x&&(a.player.Ma("onHeartbeat",x),"OK"===x.status?u=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?u=1:"LIVE_STREAM_OFFLINE"===x.status&&(u=0));a.sequenceNumber&&-1===u||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.Z=p.heartbeatServerData);hSa(a,q,t,u)}},
onError:function(p){k6(a)&&o6(a,!0,"net-"+p.status)},
onTimeout:function(){k6(a)&&o6(a,!0,"timeout")}};
c.mf()&&(b.aJ="Bearer "+c.mf());g.Ev(a.ma,"player/heartbeat",h,b)},hSa=function(a,b,c,d){-1===d?(b="decode "+g.yc(g.fb(c),3),o6(a,!1,b)):2===d?(p6(a),a.D=!0):(a.S=0,a.u.stop(),1===d?(a.D=!1,a.player.Jf("heartbeat.stop",a.pe(c)),g.cw("heartbeatActionPlayerHalted",jSa(b))):(a.D=!0,c=0,a.C&&b&&(c=cSa(a,b),a.player.ea("livestatedata",b)),c?n6(a,c):n6(a)))},cSa=function(a,b){var c,d,e=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,f=!(!e||!e.switchStreamsImmediately),h=kSa(e),l=a.getVideoData(),
m=a.player.zb(a.getPlayerType()),n=m.Dc()&&!g.AG(l)&&!a.player.isAtLiveHead(a.getPlayerType());
if(g.pG(l)){var p=(null===(c=a.player.hd())||void 0===c?void 0:c.Hb())||{};p.status=b.status||"";p.dvr=""+ +n;p["switch"]=""+ +f;p.ended=""+ +!(!e||!e.displayEndscreen);a.player.Ca("heartbeat",g.xD(p))}if(n&&!f)return h;f=e&&e.streamTransitionEndpoint&&e.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(e&&e.transitionTiming))a.getVideoData().OK=f;else{if(n=f)(n=f&&f.videoId)?(a.player.Pj(n,void 0,void 0,!0,!0,f),a.Rz("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),n=!0):n=!1;if(n)return h}if("OK"===b.status.toUpperCase()){f=e&&e.broadcastId;n=a.i&&a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer&&a.i.liveStreamability.liveStreamabilityRenderer.broadcastId;p=f!==n&&(null!=f||a.player.N("web_player_heartbeat_undefined_killswitch"));if(!l.hlsvp&&!l.jb||p)return e={video_id:l.videoId},l.iH&&(e.is_live_destination="1"),a.player.N("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=l.watchNextResponse),
e.autonav_state=l.autonavState,e.oauth_token=l.oauthToken,e.force_gvi=l.bh,e.zi=l.zi,8===a.player.getPresentingPlayerType()&&a.player.Bo(8),m=void 0,l.hlsvp||l.jb?p&&(m=new j6("broadcastIdChanged",n+","+f),a.Rz("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(f&&(m=new j6("formatsReceived",""+f)),a.Rz("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(e,void 0,void 0,
void 0,m),h;a.player.Md("heartbeat",a.getPlayerType())}e&&e.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.yb&&a.api.zt()):g.VJ(m)&&(l=(null===(d=a.player.hd())||void 0===d?void 0:d.Hb())||{},a.player.Ca("hbse",g.xD(l),!0),a.player.zt(),a.player.Ma("onLiveMediaEnded",b)));return h},kSa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},o6=function(a,b,c){if(!a.u.isActive()){a.u.stop();
a.S++;var d=a.getVideoData();if(d.lH||b&&!g.vG(a.getVideoData())&&!m6(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.bx)?f=a.heartbeatParams.bx:f=d.kH||5;e=a.S>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=jSa()),g.cw("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Jf(b,"Video playback interrupted. Please try again.",c):a.player.Jf(b,"Sorry, there was an error licensing this video.",
c)):(n6(a,a.I.getValue()),g.ae(a.I))}},jSa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},p6=function(a){a.S=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},bSa=function(a){var b,c=a.getVideoData(),d=a.player.V();
if(c.isLivePlayback)if(g.lE(d.B)){a.C=!0;a.K=!0;if(!g.$E(d)||g.lF(d))a.offlineSlate=new h6(a.player),g.I(a,a.offlineSlate),g.JM(a.player,a.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(a.i=c.playabilityStatus);if("UNPLAYABLE"!==(null===(b=a.i)||void 0===b?void 0:b.status)||a.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.i?(c=kSa(a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer))?n6(a,c):n6(a,7500):n6(a,1E3)}else a.player.Jf("html5.unsupportedlive",
"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!d.N("html5_release_post_live_heartbeat_killswitch")&&g.Sb(c.Aa,"heartbeat")&&a.player.Md("heartbeat",a.getPlayerType())},iSa=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},fSa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},eSa=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],lSa={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),
SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),
SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},q6=lSa;q6=lSa;g.k=c6.prototype;g.k.bK=q6.FIRSTDAYOFWEEK;g.k.cK=q6.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new c6(this.date);a.bK=this.bK;a.cK=this.cK;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.add=function(a){if(a.u||a.i){var b=this.getMonth()+a.i+12*a.u,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(c=this.getFullYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),
this.date.setFullYear(a.getFullYear()+b),this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),b6(this,a.getDate()))};
g.k.toString=function(){return[this.getFullYear(),ORa(this.getMonth()+1),ORa(this.getDate())].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.w(d6,g.FN);d6.prototype.hide=function(){this.i&&this.i.removeAttribute("aria-haspopup");g.FN.prototype.hide.call(this)};
d6.prototype.show=function(){this.i&&this.i.setAttribute("aria-haspopup","true");g.FN.prototype.show.call(this)};
d6.prototype.xa=function(){(0,g.ie)(this.B);g.FN.prototype.xa.call(this)};g.w(e6,g.W);
e6.prototype.I=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;f6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.i&&this.i.yb)this.i.Eb();else{var b=VRa(this);b&&this.B(b.serviceEndpoint||b.command);b=g.r(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.i||(this.i=new d6(this.J,this.D),this.i.Da(this.element),g.I(this,this.i),this.i.subscribe("reminderMenuItemClicked",this.B,this));b=this.i;b.menuPopupRenderer=a;TRa(b)}};
e6.prototype.B=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(XRa(this,c,b.params),a=g.r(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;f6(this);break}}};g.w(h6,g.W);g.k=h6.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Qa=function(a){var b,c,d=null===(c=null===(b=null===a||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate;if(d){this.u=a;d=d.liveStreamOfflineSlateRenderer;d.canShowCountdown?this.AO():i6(this,d);var e,f,h,l,m=null===(l=null===(h=null===(f=null===(e=null===a||void 0===a?void 0:a.liveStreamability)||void 0===e?void 0:e.liveStreamabilityRenderer)||void 0===f?void 0:f.offlineSlate)||void 0===h?void 0:h.liveStreamOfflineSlateRenderer)||
void 0===l?void 0:l.thumbnail;if(m){e=0;f=null;m=m.thumbnails;for(h=0;h<m.length;h++)m[h].width>e&&(e=m[h].width||0,f=m[h].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";d.actionButtons||d.reminderButton?(this.i||(this.i=new e6(this.api),this.i.Da(this.Fa("ytp-offline-slate-buttons")),g.I(this,this.i)),URa(this.i,d.actionButtons&&d.actionButtons[0],d.reminderButton)):this.i&&URa(this.i,null,null);this.u=a}else this.u=null;this.DO()};
g.k.DO=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.zb(),d=this.getVideoData();b=d.isLivePlayback&&(g.VJ(c)||g.T(c,2)||g.T(c,64));var e=2===d.autonavState&&g.T(c,2);c=c.Dc()&&!g.AG(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.yb?(null===a||void 0===a?0:g.XH(a,2))&&!this.getVideoData().Wi&&(g.Uq(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Uq(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ea("offlineslatestatechange"),
this.I&&this.api.zt()):this.yb&&(this.hide(),this.api.ea("offlineslatestatechange"))};
g.k.AO=function(){var a,b,c,d,e=null===(d=null===(c=null===(b=null===(a=this.u)||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate)||void 0===d?void 0:d.liveStreamOfflineSlateRenderer;if(e){var f=Math.floor(g.Qa()/1E3),h=e.canShowCountdown&&Number(e.scheduledStartTime);!h||h<=f?(i6(this,e),this.countdownTimer.stop()):(f=g.GL(h-f),i6(this,e,f),g.Lq(this.countdownTimer))}};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.xa.call(this)};j6.prototype.u=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.i===a.i:!1};
j6.prototype.isExpired=function(){return 6E4<(0,g.Q)()-this.B};
j6.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.i};g.w(l6,g.WM);g.k=l6.prototype;g.k.xa=function(){p6(this);this.player.Xe("heartbeat");g.WM.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.K=!0;n6(this,2E3)};
g.k.Ew=function(a){this.heartbeatParams=a;n6(this,2E3)};
g.k.pQ=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null===(b=this.i)||void 0===b?void 0:b.status)&&!this.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.T(a.state,2)||g.T(a.state,64)?(p6(this),this.C&&(this.K=!0,n6(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&n6(this,2E3))};
g.k.qQ=function(){3!==this.player.getPresentingPlayerType()&&n6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Ki=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.Rz=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.cw("heartbeatActionPlayerTransitioned",a)};
g.k.pe=function(a){var b="LICENSE",c=fSa(a);if(c)return c.reason||g.zN[b]||"";(a=a.match(gSa))&&(a=Number(a[1]))&&(b=g.zra(a));return g.zN[b]||""};
g.k.ew=function(){return!!this.offlineSlate&&this.offlineSlate.yb};
var gSa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.VM("heartbeat",l6);})(_yt_player);
